### ISSUE TITLE
如果用来训练crnn，要怎么生成单行文本的图？各种增强效果怎么样？

### ISSUE THREAD

**Issue by nissansz** [Mactarvish/ocr-sample-generator#1]
如果用来训练crnn，要怎么生成单行文本的图？各种增强效果怎么样？

**Comment by Mactarvish** [comment]
感谢关注，已支持生成训练识别模型的单行文本，拉取最新版本然后在配置文件中添加 `SAVE_RECTIFIED_LINES_SEPARATELY = True` 即可

增强会有一定的效果，但是也得具体场景具体分析，建议用该工具生成一批样本训练baseline模型，然后基于baseline的权重使用你的业务数据进行二次训练。

**Comment by nissansz** [comment]
谢谢。
我在想怎么改你的代码，
实现以下功能，
每行文字标注的框，按标点和空格分割开。
可以修改下，发这种功能的代码吗？

![image](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/6215b767-0e13-47e3-af94-57c5050f40be)

另外，我用paddleocr训练检测模型时，有的图，会出现这种情况，检测不出单元格单字，怎么生成样本加强？
![image](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/389b62d0-3336-47e4-a25a-39cd199e5321)

**Comment by nissansz** [comment]
还有就是模拟生成表格，然后导出单元格标注，表格结构标注等

**Comment by Mactarvish** [comment]
> 谢谢。 我在想怎么改你的代码， 实现以下功能， 每行文字标注的框，按标点和空格分割开。 可以修改下，发这种功能的代码吗？
> 
> ![image](https://private-user-images.githubusercontent.com/41010669/293582023-6215b767-0e13-47e3-af94-57c5050f40be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTExNjQsIm5iZiI6MTcwNDExMDg2NCwicGF0aCI6Ii80MTAxMDY2OS8yOTM1ODIwMjMtNjIxNWI3NjctMGUxMy00N2UzLWFmOTQtNTdjNTA1MGY0MGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDEyMDc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMjhiYTc5MGU2NmE1MTZjZDM5NWM3YTFiZGMwZDMwZWI4N2U3YTRjYThkOWIyMWY0ZmUxYjQ0NDEyNDRhMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1WRKkeU3tlDKBhjHcpx8R8cHQvuS888FOUdrdR14c5M)
> 
> 另外，我用paddleocr训练检测模型时，有的图，会出现这种情况，检测不出单元格单字，怎么生成样本加强？ ![image](https://private-user-images.githubusercontent.com/41010669/293582060-389b62d0-3336-47e4-a25a-39cd199e5321.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTExNjQsIm5iZiI6MTcwNDExMDg2NCwicGF0aCI6Ii80MTAxMDY2OS8yOTM1ODIwNjAtMzg5YjYyZDAtMzMzNi00N2U0LWEyNWEtMzljZDE5OWU1MzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDEyMDc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNWQyYzFhMWQ3YTI0ZDk3OTM0MGEyYzVhNGQxZGIxN2QyYzU4YjdjMmQ4Zjc4Njk4MzRmN2MwMjQ5MzVhOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DuiG8DOR-DdfZa8agQq7Ozwf6wSo3icL6i9OXnlmo2k)

1. 可以实现，修改`generate_ptext_instance`函数的生成文本内容的逻辑即可，把标点符号空格等字符放在实例的最后，具体需要你自己做
2. 你给的这个示例图中漏检的内容大多是手写文本，这种情况最好的办法是补充该类别的训练数据，直接拿印刷体数据训练模型是很难召回手写体的，或者你找一些看着像手写体的字体文件进行合成

另外，你给的这个case是表格场景，这种情况通常先做表格识别，把每个单元格分割出来，后边的文本检测和识别就好做了
表格样本合成的方法有很多，具体请自行调研

**Comment by nissansz** [comment]
我想在同一句话的标点处切割标注，不换行，要怎么修改

**Comment by nissansz** [comment]
如果用表格坐标标注用于文本行检测训练，有什么不好的影响吗？

![border_3_FHIV20BI9JD7LP0UCGSM](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/396c47da-3f60-4030-ab1c-f1470422d628)
 
![border_0_6JSD8O0XKZIGLEOU6SBN](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/38e9553c-5414-498e-aa2d-8e5d08914b05)

![border_1_1QKB7AQZ08T62BMXGF8H](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/60c67e0a-9b46-4bd4-87bc-c0b7d7972145)

![border_2_5TNDHZP2I6GIMEF3W039](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/33b962aa-fe8f-40f7-912f-987009b98a06)

**Comment by Mactarvish** [comment]
> 我想在同一句话的标点处切割标注，不换行，要怎么修改

有点麻烦，可以在Instance里再定义一个方法，用于查询标点的坐标然后把一个Instance转换成两个

一般来说目标检测的标注要求拉框紧贴目标，这样训出来的模型精度最好，直接用单元格坐标作为框肯定能训，但是效果会差些，而且用这样的模型检测出来的结果训crnn的时候还得额外标注空格

**Comment by nissansz** [comment]
![image](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/abb01bdd-45ad-4f1d-aa38-18b358115872)
现在用表格生成方法可以得到类似上面的效果，用于ctpn训练效果可以？
要用哪些增强方法？

**Comment by nissansz** [comment]
如果生成一些这种图片，用于训练有什么不好的影响吗？每个instance之间的jiang间距如何设定为2个空格？

![mix_00010](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/1cd730bf-8a0b-4b3e-9de6-3773066dadd4)
![mix_00011](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/bac4ca57-7623-453c-9d82-11716040b30f)
![mix_00012](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/1d9b2112-eaf2-4d29-8d06-ba9f831a8edf)

**Comment by Mactarvish** [comment]
> ![image](https://private-user-images.githubusercontent.com/41010669/293612992-abb01bdd-45ad-4f1d-aa38-18b358115872.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzQ0MDgsIm5iZiI6MTcwNDE3NDEwOCwicGF0aCI6Ii80MTAxMDY2OS8yOTM2MTI5OTItYWJiMDFiZGQtNDVhZC00ZjFkLWFhMzgtMThiMzU4MTE1ODcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA1NDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NmU4NTkwMGI3NjlkOTdhM2QwMzMwMGExNjQ5YmM2Nzk5YjdkN2MyYWNlOTgzYTA0MWFkNjk0ODI0MjExZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ewYU76FPIse531h4FMKM1APixk69baj0Xf-QNXnBVs) 现在用表格生成方法可以得到类似上面的效果，用于ctpn训练效果可以？ 要用哪些增强方法？

用不用增强，用什么增强，取决于你的业务场景，没有统一的方法，增强的目的是拓展样本分布，使训练分布和真实分布尽量接近

**Comment by Mactarvish** [comment]
> 如果生成一些这种图片，用于训练有什么不好的影响吗？ ![mix_00028](https://private-user-images.githubusercontent.com/41010669/293627754-4a4a06ee-f4eb-496b-864b-86a34915127b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzQ2NjAsIm5iZiI6MTcwNDE3NDM2MCwicGF0aCI6Ii80MTAxMDY2OS8yOTM2Mjc3NTQtNGE0YTA2ZWUtZjRlYi00OTZiLTg2NGItODZhMzQ5MTUxMjdiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA1NDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYjdiNDFmMjVmYTY0ZDdmMDRhMWY4NDFmOGUxOTUyMDRmZDY5NzNhN2U1YmIzZDE5NDJlNGI0YmM0YWZhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cfhdeUkgvsU00Kb8goU2dISPF7wmf7wRgEPqfzcU1zI) ![mix_00029](https://private-user-images.githubusercontent.com/41010669/293627758-21910d3a-80f8-407b-bf5e-4404d118b834.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzQ2NjAsIm5iZiI6MTcwNDE3NDM2MCwicGF0aCI6Ii80MTAxMDY2OS8yOTM2Mjc3NTgtMjE5MTBkM2EtODBmOC00MDdiLWJmNWUtNDQwNGQxMThiODM0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA1NDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNDE1MjYyMGU5MDA3YmZmNTZkZmQ5NjU1NjE2MTQ3ZmQ2ZDVmNThiMjA4ZDVhOTE3ZjAxNTczYzM0MTkxNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9KU3iKuaoO6a3n_ekRzcmpBtqAYd4m9K1ee0J4H0RCY) ![mix_00026](https://private-user-images.githubusercontent.com/41010669/293627761-08e090ca-b037-46ed-abf1-1a7cff367203.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzQ2NjAsIm5iZiI6MTcwNDE3NDM2MCwicGF0aCI6Ii80MTAxMDY2OS8yOTM2Mjc3NjEtMDhlMDkwY2EtYjAzNy00NmVkLWFiZjEtMWE3Y2ZmMzY3MjAzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA1NDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYmQwYmUxMjAwMzlkZTQ0NDQ0MDNiMjQ5NTYzMzM4ZWZhYTNjNmJjOGY5YTc2YjNkNTc5MTQwZjIxNTY5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mv8ZUdlW4nGroQczIvnuvhZIPU5YEwvk-7wnP-SlQhM) ![mix_00027](https://private-user-images.githubusercontent.com/41010669/293627762-63d50436-89e0-4b99-81ef-6105ad550ff1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzQ2NjAsIm5iZiI6MTcwNDE3NDM2MCwicGF0aCI6Ii80MTAxMDY2OS8yOTM2Mjc3NjItNjNkNTA0MzYtODllMC00Yjk5LTgxZWYtNjEwNWFkNTUwZmYxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA1NDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MmU2NDVlZTQyZDM0ODFmNzk0ODg3MDFmMTk3MGFmNjk4MzhmNmYwODJkMzE3ZjNmNjRlM2UyZjVkNDQwODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aQOYA8K7NzcbgUGJyF603aBW0JGQ94bVfdGlRXiJE8c)

你生成的这些图像用的是哪个config？有很多空的特别小的框，这些错误的gt训练可能导致模型不收敛

**Comment by nissansz** [comment]
就是用mix config生成，
空的小框会在标签转换为paddle格式时删掉

**Comment by Mactarvish** [comment]
那就没啥问题，效果好不好主要取决于这些合成的图和你的测试集是不是一致
另外就是不要把字体调的太小，太小的目标检测比较困难

**Comment by nissansz** [comment]
我是想训练通用的检测模型，
如果想模拟ppt那种彩底，白字效果，要怎么改一改？

听一个朋友说，他训练放了10几种效果训练

**Comment by nissansz** [comment]
在生产同行内的不同实例时，怎样获取实例的text，如果不是想要的text，再重新调用生成方法，生成视力段

**Comment by nissansz** [comment]
drawer.text(xy=(tl_x, tl_y), text=text, fill=(255, 255, 255),stroke_fill=(0, 0, 0), font=font)
                drawer.text(xy=(tl_x, tl_y), text=c, fill=(255, 255, 255), stroke_fill=(0, 0, 0), font=font)
把写文字，颜色改为白色，背景用彩图，结果，看不到字了，而且背景也变白了，我想在彩图上写白字黑边框的文字，要怎么改？

![mix_00006](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/67d55075-ea7c-499b-b0dd-9f222b506c4a)

**Comment by Mactarvish** [comment]
不要太执着于增广，增广适可而止，太多的增广不见得一定会有增益
背景变白是背景增广器的线性系数不合适，调整一下就行了

**Comment by nissansz** [comment]
注销掉这些，还是没法显示彩底

 iaa.Sometimes(0.1,
                iaa.AdditiveGaussianNoise(scale=0.5*2),
            ),
            iaa.Sometimes(0.1,
                iaa.SaltAndPepper(),
            ),

**Comment by Mactarvish** [comment]
。。不是注销，是让你修改AddBackground的alpha

**Comment by nissansz** [comment]
改了0.9-1可以显示背景了，但是字又模糊了，字的透明度在哪设置？
![mix_00003](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/8b68dd9f-b42c-4441-9767-8f5e902136e5)

**Comment by Mactarvish** [comment]
这个得修改一下AddBackgound的实现，现在是背景前景线性混合，背景的系数高了前景就低了，看起来也就变浅了
一个可能的方案是根据字的灰度值生成一个mask，比如0,0,0的区域不参与混合，这样可以做出你想要的效果
实现了之后你提交一个pull request，我给你合并进来

**Comment by Mactarvish** [comment]
更好的方法，你关掉AddBackground，直接在创建画布的时候把画布设置成你想要的背景，然后后续就直接在这个背景上渲染文字了，这样彻底解决前景变浅的问题

**Comment by nissansz** [comment]
![mix_00003](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/5dbd16d6-5e9a-42c4-9758-b3c42d3fc86d)
好像可以了，改了这个代码
        # self.canvas_pil = canvas_pil

        self.background_dir = r'F:/pycharm2020.2/ocr-sample-generator-develop/assets/backgrounds'
        self.bg_image_paths = glob.glob(os.path.join(self.background_dir, "*.jpg")) + \
                                glob.glob(os.path.join(self.background_dir, "*.png"))
        src_bg_path = random.sample(self.bg_image_paths, 1)[0]
        # 读取图片
        img = Image.open(src_bg_path)
        # # 创建Pillow canvas
        # canvas = ImageDraw.Draw(img)
        self.canvas_pil = img

**Comment by nissansz** [comment]
![mix_00007](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/58d23b29-ca55-4588-aa76-3cbe15d287df)

增加随机填充颜色效果，还可以

**Comment by nissansz** [comment]
如果要模拟下图中小字这种效果，要怎么修改参数或代码？
![image](https://github.com/Mactarvish/ocr-sample-generator/assets/41010669/d0b1d176-36fe-4afa-9809-5d31348285fc)

**Comment by Mactarvish** [comment]
下载对应的字体，然后在pil渲染的逻辑中设置斜体

**Comment by nissansz** [comment]
关键是模糊的小字，字体按大小，和模糊的模拟

**Comment by Mactarvish** [comment]
模糊也有很多种，可以试试高斯模糊或者质量压缩都可以产生模糊的效果
大小直接调整font_size就行了
