### ISSUE TITLE
请教一下，每个语种的语料库或词库要怎么准备。把字体里的单字符提取出来放到语料库，每行做一条？其余要每个字组个词放进去吗？不知道怎么准备均衡的源数据用来生成句子

### ISSUE THREAD

**Issue by nissansz** [Mactarvish/ocr-sample-generator#3]
请教一下，每个语种的语料库或词库要怎么准备。把字体里的单字符提取出来放到语料库，每行做一条？其余要每个字组个词放进去吗？不知道怎么准备均衡的源数据用来生成句子

**Comment by Mactarvish** [comment]
你好
汉字字典是 `assets/zidian_new_5883.txt` 文件，英文就是26个字母大小写，不同语种的比例通过配置文件的`CONTEXT`字段进行设置
字符是最小单位，不存在词库这个概念，这个程序在生成样本的时候是随机选择字符随机排列的
不需要从字体中抽取字符，只要把需要的字体文件放在`assets/fonts/`里头就行了，程序会随机选择字体并生成
事实上在生成样本的时候也不应该刻意地生成某些句子或者单词，只要均匀覆盖到你的数据分布，那么越杂乱多样，训练效果越好

**Comment by nissansz** [comment]
检测样本可以随机。如果是Crnn字符识别，应该是用语料库吧？

**Comment by Mactarvish** [comment]
crnn也是一个字符一个字符地识别，只要样本中有你需要的字符就行了，没必要刻意组成有意义的单词或句子

**Comment by nissansz** [comment]
好像有个双向lstm概念，有相关

**Comment by Mactarvish** [comment]
跟单向双向没啥关系，单向lstm也是建模序列关系的，字符级别的识别也是会对单个字符的左右结构进行建模
单词级别的识别也可以做，重新实现一下 `generate_ptext_instance`函数把text改成你预设好的就行了
不过通常没有必要，这么搞就只能识别固定的单词了，字符级别的识别可以满足95%以上的实际业务需求

**Comment by nissansz** [comment]
如果有些容易混淆的字符，识别错，该怎么增加样本？增加多少？

**Comment by Mactarvish** [comment]
可以在字典里把这些字符多重复几遍， 或者生成的时候根据内容做个过滤
增加多少没有固定的说法，看着办吧

**Comment by nissansz** [comment]
每张图片字符数，比如我大多数使用20个字符和大多数使用几个字符，这两种图片作为训练数据哪种好？

**Comment by Mactarvish** [comment]
看你实际推理的时候是多少个字符了

**Comment by nissansz** [comment]
字数就一般段落，25字以内

**Comment by nissansz** [comment]
每次重新开始恢复训练时，近似的字，好像就会变错，例如 2->Z, 0->O，这种只能继续训练，逐渐改善，还有没有其它办法？

**Comment by nissansz** [comment]
有没有类似布丁扫描的AI文档修复的python代码

**Comment by nissansz** [comment]
看许多python独立程序，解压出来会自带各种环境和包，那种是怎么打包实现的？
